---
title: "Plotly"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Loading NYC Restaurant Inspection Data
```{r}
rest_inspec = 
  rest_inspec
```


```{r}
rest_inspec %>% 
  count(cuisine_description) %>% 
  arrange(desc(n))

```

```{r}
rest_inspec =   
rest_inspec %>% 
  select(boro, critical_flag, cuisine_description, dba, inspection_date, score, zipcode, grade, building) %>% 
    mutate(cuisine_description = recode(cuisine_description, `Café/Coffee/Tea` = "Cafe", `Latin (Cuban, Dominican, Puerto Rican, South & Central American)` = "Latin")) %>% 
  filter(grade %in% c("A", "B", "C", "Z", "P"),
         cuisine_description %in% c("Latin", "Italian", "Cafe", "Mexican", "Japanese", "Caribbean", "Bakery")) 

```


Random sample 

```{r boxplot}
rest_inspec %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>% 
  plot_ly(y = ~score, color = ~cuisine_description, type = "box", colors = "viridis")
```


```{r histogram}
rest_inspec %>% 
  group_by(boro, cuisine_description) %>% 
  count(boro) %>% 
  mutate(boro = fct_reorder(boro, n)) %>% 
  plot_ly(x = ~boro, y = ~n, type = "bar", color = ~cuisine_description)
```



```{r timeplot}

rest_inspec %>% 
  group_by(inspection_date) %>% 
  summarize(
    mean_score = mean(score)) %>% 
  plot_ly(type = 'scatter', mode = 'lines') %>% 
  add_trace(x = ~inspection_date, y = ~mean_score)
  
```


